const Languages = {
  tabs: {
    product: "Sản phẩm",
    assets: "Tài sản",
    topUp: "Nạp tiền",
    transactions: "Giao dịch",
    help: "Trợ giúp",
    withdraw: "Rút tiền",
  },
  common: {
    cancel: "Huỷ",
    OK: "Chọn",
    back: "Quay lại",
    yes: "Có",
    no: "Không",
    close: "Đóng",
    search: "Tìm kiếm",
    agree: "Đồng ý",
    or: "Hoặc",
    continue: "Tiếp tục",
    currency: "VND",
    percent: "%",
    addBank: "Thêm tài khoản",
    updateBank: "Cập nhật tài khoản",
    notAccount: "Bạn chưa có tài khoản",
    hasAccount: "Bạn đã có tài khoản",
    news: "Tin tức",
    historyTransaction: "Lịch sử giao dịch",
    skip: "Bỏ qua",
    notFound: "Không tìm thấy dữ liệu",
  },
  errorMsg: {
    noInternet: "Kết nối bị gián đoạn, vui lòng thử lại!",
    sessionExpired: "Phiên làm việc hết hạn, vui lòng thử lại!",
    userNameRequired: "Họ và tên không được để trống",
    userNameLength: "Họ và tên không được ít hơn 8 ký tự",
    userNameRegex: "Không được chứa ký tự đặc biệt hoặc số",
    errIllegal: "Mật khẩu không hợp lệ",
    emailNull: "Email không được để trống",
    emailRegex: "Email không đúng định dạng",
    cardNull: "Số CMND/CCCD không được để trống",
    cardRegex: "Số CMND/CCCD phải là số",
    cardCheck: "Số CMND/CCCD không hợp lệ",
    pwdNull: "Mật khẩu không được để trống",
    pinNull: "Mã pin không được để trống",
    pwdCheck: "Mã pin phải gồm 6 ký tự số",
    conFirmPwd: "Xác nhận mã pin không trùng khớp với mã pin",
    emptyAmount: "Bạn chưa nhập số tiền",
    minAmount: "Số tiền nạp/rút tối thiểu là 100.000 vnđ",
    phoneIsEmpty: "Số điện thoại không được để trống",
    phoneRegex: "Số điện thoại không đúng định dạng",
    phoneCount: "Số điện thoại chỉ được 10 số",
    jobEmpty: "Nghề nghiệp không được để trống",
    taxIdEmpty: "Mã số thuế không được để trống",
    taxIdSyntax: "Mã số thuế không được ít hơn 10 ký tự",
    specialCharacters: "Không được chứa kí tự đặc biệt",
    birthdayEmpty: "Chưa cập nhật",
    birthdayNotNumber: "Ngày sinh không đúng định dạng ví dụ: 1970-01-01",
    birthdayAge18: "Chưa đủ 18 tuổi",
    birthdayAge95: "Vượt quá 95 tuổi",
    errProvince: "Thành phố không được bỏ trống",
    errDistrict: "Quận huyện không được bỏ trống",
    errWard: "Xã phường không được bỏ trống",
    errFunds: "Nguồn tiền không được bỏ trống",
    errMoveto: "Chuyển tới không được bỏ trống",
    errKeyBook: "Mã sổ không được bỏ trống",
    errMsgOldPwdCompare: "Mật khẩu cũ bạn nhập không đúng",
    errMsgCurrentPwdCompare: "Mã pin nhập lại không trùng khớp",
    errMsgEmpty: "Mật khẩu không được để trống",
    errMsgCodeEmpty: "Mã pin không được để trống",
    errMsgLength: "Mật khẩu phải từ 8 kí tự trở lên",
    errMsgSpecialChar: "Mật khẩu nhập không được chứa kí tự đặc biệt",
    errMsgSpaceChar: "Mật khẩu nhập không được chứa kí tự trống",
    errMsgUpperChar: "Mật khẩu phải có 1 kí tự in hoa",
    errMsgGender: "Giới tính không được bỏ trống",
    uploading: "Đang tải ảnh lên",
    uploadingError: "Tải ảnh thất bại",
    errStk: "Số tài khoản hoặc số thẻ vượt quá giới hạn cho phép",
    errStkEmpty: "Số tài khoản hoặc số thẻ trống",
    errNameEmpty: "Tên tài khoản ngân hàng trống",
    errBankEmpty: "Ngân hàng chưa được chọn",
    errMethodMoney: "Vui lòng cập nhật phương thức nhận tiền",
    errMethodWithdrawMoney: "Vui lòng cập nhật phương thức rút tiền",
    errChooseMethodMoney: "Vui lòng chọn phương thức nhận tiền",
    errNoEnoughMoney: "Hạn mức giao dịch tối thiểu <br />100.000 VND",
    errLimit: "Số dư hiện tại không đủ để giao dịch",
    updatePwd: "Xác nhận thay đổi mã pin thành công",
    errEmptyBirthday: "01/01/1920",
    errKYC: "Vui lòng xác thực CMT/CCCD để thực hiện việc rút tiền",
    notKYc: " chưa xác thực CMT/CCCD",
    waitKYC: " đang chờ xác thực CMT/CCCD",
    waitMesKYC:
      " Chúng tôi đang xác thực chứng từ của bạn. Vui lòng đợi trong giây lát.",
    copied: "Đã sao chép",
    qrCodeDownloaded: "Đã tải ảnh Qr-Code thành công",
    topupSuccess: "Univest đã nhận được khoản tiền của bạn.",
    errSyntaxBank: "Số tài khoản ngân hàng tối thiểu 3 kí tự số",
    errSyntaxATM: "Số thẻ ATM phải đủ 16 hoặc 19 kí tự số",
    errNotNumberBank: "Số thẻ ngân hàng phải là kí tự số",
    errNotNumberATM: "Số thẻ ATM phải là kí tự số",
    errOTP: "Đã có lỗi xảy ra! Vui lòng gửi lại mã OTP",
    errReferral: "Vui lòng nhập mã giới thiệu",
  },
  biometry: {
    useFingerprint: "Đăng nhập bằng vân tay của bạn",
    useFingerPrintError: "Vân tay không khớp, vui lòng thử lại.",
    useFingerPrintManyTimesError:
      "Bạn đã nhập sai quá nhiều lần, vui lòng nhập mã pin.",
  },
  noInternet: {
    offline: "Kết nối bị gián đoạn",
    desNoInternet: "Kết nối bị gián đoạn, vui lòng thử lại!",
  },
  location: {
    PermissionAlert: "PermissionAlert",
    AccessLocationServices: "AccessLocationServices",
    OpenSetting: "OpenSetting",
    Cancel: "Cancel",
  },
  image: {
    camera: "Camera",
    library: "Thư viện ảnh",
    permissionAlert: "Yêu cầu truy cập",
    accessPhotoMsg: "Univest cần truy cập vào thư viện ảnh của bạn",
    accessCameraMsg: "Univest cần truy cập vào camera của bạn",
    accessAddPhotoMsg: "Univest cần thêm ảnh vào thư viện ảnh của bạn",
    openSetting: "Mở cài đặt",
    deny: "Từ chối",
    uploading: "Đang tải ảnh",
    singleUploading: "Đang tải ảnh lên",
    selectedThumb: "Đã chọn hình đại diện",
    selectAsThumb: "Đặt làm hình đại diện",
    uploadFailed: "Xảy ra lỗi trong quá trình tải ảnh lên",
  },
  onBoarding: [
    {
      title: "Uy tín 5 sao",
      des: "Univest được tin tưởng bởi các nhà đầu tư tín dụng uy tín. Hơn 100.000.000 người dùng tin tưởng và sử dụng",
    },
    {
      title: "Kiếm tiền mọi lúc mọi nơi",
      des: "Univest với các gói đầu tư đa dạng với lãi suất khủng, bạn có thể kiếm tiền ngay cả khi đang ngủ !",
    },
    {
      title: "Tích luỹ cho tương lai",
      des: "Univest tích luỹ dài hạn với lãi suất lên tới 4% / năm. Đầu tư ngay nền móng cho tương lai",
    },
  ],
  home: {
    title: "Trang chủ",
  },
  screenNames: {
    login: "Login",
  },
  slogan: {
    title: "x2 lợi nhuận từ dòng tiền",
  },
  auth: {
    phone: "Số điện thoại",
    name: "Họ và tên",
    referral: "Mã giới thiệu",
    pwd: "Mật khẩu",
    pinCode: "Mã pin",
    saveInfo: "Lưu thông tin đăng nhập",
    login: "Đăng nhập",
    repeatPwd: "Nhập lại mã pin",
    email: "Email",
    register: "Đăng ký",
    forgotPwd: "Quên mật khẩu",
    otherLogin: "Tài khoản khác",
    textLogin:
      "<c><b>Đăng nhập</b> để sử dụng những tiện ích \ntốt nhất tới từ chúng tôi</c>",
    textRegister:
      "<a><b>Thông tin quan trọng </b> này giúp chúng tôi bảo vệ tài sản của bạn</a>",
    loginWith: "Hoặc đăng nhập với",
    registerWith: "Hoặc đăng ký với",
    policy:
      "<p>Tôi đã đọc và đồng ý với <r><u>điều khoản sử dụng</u></r> của Univest</p>",
    commit:
      "<p>Tôi cam kết đã <r>trên 18 tuổi</r> và mang quốc tịch <r>Việt Nam</r></p>",
    note: " Nhập họ và tên đầy đủ, có dấu theo CMND/CCCD",
    key: "Mọi thông tin của bạn đều được bảo mật",
    oneUppercase: "Có ít nhất 1 ký tự in hoa",
    oneCharacter: "Có ít nhất 1 ký tự đặc biệt",
    min8: "Tối thiểu 8 ký tự",
    oneCapLower: "Có ít nhất 1 ký tự in thường",
  },
  topUp: {
    amount: "Nhập số tiền bạn muốn nạp",
    amountWithdraw: "Nhập số tiền bạn muốn rút",
    placeHolder: "0",
    confirm: "Xác nhận",
  },
  product: {
    hotNews: "Hôm nay có gì mới",
    productIsSelling: "Sản phẩm của Univest",
    unlimitedAccumulation: "Tích lũy không kỳ hạn",
    accumulation1: "Tích lũy kỳ hạn 1 tháng",
    accumulation3: "Tích lũy kỳ hạn 3 tháng",
    accumulation6: "Tích lũy kỳ hạn 6 tháng",
    securityWarning:
      "Hãy cập nhật thông tin của bạn để đảm bảo an toàn tài khoản",
    email: "Email",
    contract: "Hợp đồng",
    any: "eKYC",
    phone: "Điện thoại",
    account: "Tài khoản",
    trust: "Univest có gì để bạn tin tưởng",
    shouldUse: "Univest được các nhà đầu tư khuyên dùng",
    joinWithCommunity: "Tham gia cộng đồng Univest",
    peopleJoining: "10.000.000 người",
    joinNow: "Tham gia ngay",
    investor: "Nhà đầu tư mới",
    product: "Sản phẩm",
    drawMoney: "Rút tiền, nạp tiền",
    utilities: "Tìm hiểu về Univest",
    information: "Thông tin của bạn",
    investNow: "Đầu tư ngay",
    intro: "Giới thiệu sản phẩm",
    tips: ["Về Univest", "Tích luỹ", "Túi Univest", "Hướng dẫn sử dụng"],
    package: "Gói",
    welcome: "Xin chào",
    today: "Today, ",
    interest: "Lợi nhuận",
    year: "/năm",
    dot: "• ",
    form: "Hình thức",
    authTip: "Đăng ký Univest ngay để x2 lợi nhuận từ dòng tiền",
  },
  assets: {
    title: "Tài sản",
    totalAccumulated: "Tổng",
    totalAssets: "Tổng tài sản",
    totalKinds: "Các loại tài sản",
    growUpByPeriod: "Tăng trưởng trong kỳ",
    percentByPeriod: "Phần trăm tăng trưởng",
    assetCardFields: [
      "Tài sản đầu kỳ",
      "Nạp vào trong kỳ",
      "Rút ra trong kỳ",
      "Tăng trưởng",
      "Tài sản cuối kỳ",
      "Tiền chờ thanh toán",
    ],
    topUp: "Nạp tiền",
    withdraw: "Rút tiền",
    accumulatedAssets: "Tài sản tích luỹ",
    bonds: "Trái phiếu",
    receivedInterest: "Lợi nhuận đã nhận",
    totalReceived: "Tổng tiền đã nhận",
    totalReceivedPending: "Tổng tiền chờ nhận",
    receivedTemp: "Lợi nhuận tạm tính tháng này",
    methodReceivedInterest: "Phương thức nhận lãi",
    balanceRealTime: "Số dư ví:",
    topUpMore: "Nạp thêm",
    convert: "Chuyển đổi",
    flow: "Dòng tiền",
    invest: "Đầu tư",
    growthOn: "Chi tiết",
    growthOff: "Thu gọn",
    reportPeriod: "Kỳ báo cáo",
    toPresent: "đến nay",
    recent: "gần đây",
    filter: [
      "Từ đầu",
      "7 ngày",
      "1 tháng",
      "3 tháng",
      "6 tháng",
      "9 năm",
      "1 năm",
    ],
    my: "Tài sản của tôi",
    referral: "Giới thiệu về sản phẩm",
    unlimited: "Không kỳ hạn",
    accumulation: "Tích luỹ",
    accumulationDetail: "Chi tiết",
    recentTransaction: "Giao dịch gần đây",
    topUpAccumulation: "Nạp tiền tích luỹ",
    withdrawAccumulation: "Rút tiền khỏi sổ",
    withdrawAccumulationToAccount: "Rút tiền về tài khoản",
    balance: "Sổ tích luỹ đang có",
    withdrawn: "Sổ tích luỹ đã rút",
    pending: "Sổ tích luỹ rút trước hạn chờ xử lý",
    interestTransaction: "Lịch sử nhận lãi",
    interestTempTransaction: "Lịch sử lãi tạm tính",
    bookInfo: "Thông tin sổ tích luỹ",
    history: "Lịch sử đáo hạn",
    withdrawBeforeDate: "Rút tiền trước hạn",
    autoExpiration: "Tự động đáo hạn",
    showMore: "Xem thêm",
    noBook: "Bạn chưa có sổ tích luỹ nào",
    withdrawSoon: "Thực hiện rút tiền trước hạn",
    bookId: "Mã sổ",
    original: "Số tiền gốc",
    startDate: "Ngày bắt đầu",
    fullInterest: "Lợi nhuận đúng hạn trước thuế",
    interestBeforeTax: "Số tiền lãi trước thuế",
    tax: "Thuế",
    interestAfterTax: "Số tiền lãi sau thuế",
    withdrawConfirm:
      "<pw><r>Chú ý:</r> Bạn có chắc chắn muốn rút tiền trước hạn không?</pw>",
    total: "Tổng tiền nhận được",
    withdrawInfo1: [
      "Khi rút đúng hạn",
      "Ngày rút đúng hạn",
      "Mức lợi nhuận đúng hạn",
      "Lợi nhuận nhận được",
      "Thuế thu nhập cá nhân",
      "Số tiền nhận được sau thuế",
    ],
    withdrawInfo2: [
      "Khi rút trước hạn",
      "Ngày nhận tiền",
      "Lãi suất rút trước hạn",
      "Lợi nhuận nhận được",
      "Thuế thu nhập cá nhân",
      "Số tiền nhận được sau thuế",
    ],
    withdrawInfo3: ["Chênh lệch", "Lợi nhuận", "Tiền lợi nhuận bị mất"],
    note: "<pp>Khi rút sổ Tích lũy trước hạn, bạn chỉ được hưởng mức lợi nhuận <r>%s</r> cho số ngày thực tế đầu tư. Thông tin cụ thể như sau:<pp>",
    expireDate: "Ngày tất toán",
    expectedExpireDate: "Ngày tất toán đúng hạn",
    remainingDay: "Số ngày còn lại",
    chooseDate: "Chọn ngày tất toán",
    periodLabel: "<as>Lợi nhuận <r>%s</r> / năm</as>",
    expiredDate: "Ngày kết thúc",
    expectedInterest: "Lợi nhuận dự tính trước thuế",
    filterTitle: "Chọn thời gian muốn xem báo cáo",
    report: "Đồng ý",
    clear: "Bỏ chọn",
    or: "Hoặc chọn ngày",
    chooseStartDate: "Từ ngày",
    chooseEndDate: "Đến ngày",
    empty: "Bạn chưa có tài sản nào",
    startInvest: "Bắt đầu đầu tư ngay",
    introduce: "Giới thiệu về Univest và tích luỹ",
  },
  accumulate: {
    intro: "Giới thiệu về",
    products: "Các sản phẩm hiện có",
    rate: " / năm",
  },
  confirmInvest: {
    title: "Xác nhận nạp tiền",
    fields: [
      "Nguồn tiền",
      "Nguồn nhận",
      "Số tiền",
      "Ngày nạp tiền",
      "Mức lợi nhuận cam kết",
    ],
    fieldAccums: [
      "Ngày bắt đầu",
      "Ngày hết hạn",
      "Mức lợi nhuận cam kết",
      "Mức lợi nhuận rút trước hạn",
      "Lợi nhuận dự kiến nhận được",
      "Thuế thu nhập cá nhân",
      "Số tiền dự kiến nhận được",
    ],
    topupAmount: "Số tiền cần nạp",
    investAmount: "Số tiền cần đầu tư",
    policy:
      "<p> Tôi đã đọc và đồng ý với <r><u>điều khoản sử dụng và chính sách/u></r> của Univest</p>",
    invest: "Đầu tư",
    cancel: "Huỷ",
  },
  confirmOtp: {
    title: "Xác nhận OTP",
    enterOTP: "Hãy nhập và xác nhận mã OTP",
    confirm: "Xác nhận",
    sendAgain: "Gửi lại mã",
    sendAgainTime: "sau",
    message:
      "<a>Mã xác thực đã được gửi đến số điện thoại <b>%s1</b> qua cuộc gọi. Mã hết hiệu lực sau 03:00 phút.</a>",
    popupOtpErrorTitle: "Thông báo OTP",
    popupOtpErrorDescription: "OTP không chính xác",
    popupOtpSuccessDescription: "Đăng ký thành công",
    popupOtpResendCode: "Mã OTP đã hết hạn. Vui lòng gửi lại",
    inputPhone: "Nhập số điện thoại",
    sendCode: "Gửi OTP cho tôi",
    inputPhoneTitle: "Hãy nhập số điện thoại",
    notePhone: "Univest sẽ gửi mã OTP qua cuộc gọi để xác nhận",
    notePhoneForgot:
      "Bạn đã quên mất mật khẩu của mình. Hãy nhập số điện thoại Univest sẽ gửi OTP qua cuộc gọi để xác nhận",
    forgotPwd: "Quên mật khẩu",
  },
  convert: {
    title: "Chuyển đổi",
    alert:
      "Khi thực hiện chuyển đổi gói tích luỹ lãi suất tăng trưởng gói cũ sẽ được tính theo lãi tăng trưởng của gói không kỳ hạn",
    funds: "Nguồn tiền",
    accumulate: "Tích luỹ không kỳ hạn với lãi suất lên tới 5% /năm",
    moveto: "Chuyển tới",
    moneyConvert: "Nhập số tiền cần chuyển đổi",
    entermoneyconvert: "Nhập số tiền cần chuyển",
    saving: "Chọn sổ tiết kiệm cần chuyển đổi",
    enterSaving: "Chọn sổ cần chuyển đổi",
    amount: "Số tiền trong sổ",
    keyBook: "Mã sổ",
  },
  quickAuThen: {
    title: "Cài đặt và bảo mật",
    quickButton: "Sử dụng xác thực nhanh",
    fingerAuThen: "Bảo mật vân tay",
    faceid: "Nhận diện khuôn mặt",
    pin: "Mã Pin",
    changePwd: "Chỉnh sửa mật khẩu",
    changePinCode: "Chỉnh sửa mã pin",
    confirm: "Xác thực của bạn",
    useFaceId: "Đăng nhập nhanh bằng Face ID",
    useTouchId: "Đăng nhập nhanh bằng vân tay",
    facIdConFirm:
      "Quý khách có muốn sử dụng Face ID làm phương thức xác thực chính",
    touchIdConfirm:
      "Quý khách có muốn sử dụng vân tay làm phương thức xác thực chính",
    passcodeConfirm:
      "Quý khách có muốn sử dụng mã pin làm phương thức xác thực chính",
    description: "Đăng nhập bằng vân tay của bạn",
    useFaceID: "Sử dụng Face ID để đăng nhập vào Univest",
    useTouchID: "Sử dụng Touch ID để đăng nhập vào Univest",

    goToSetting: "Cài đặt",
    desSetPasscode: "Vui lòng thêm mã PIN để cài đặt xác thực nhanh",
    desSetTouchId: "Vui lòng thêm vân tay để xác thực nhanh",
    desSetFaceId: "Vui lòng thêm Face ID để xác thực nhanh",
    successAddTouchId: "Đã thêm vân tay vào xác thực nhanh của bạn",
    successAddFaceId: "Đã thêm Face ID vào xác thực của bạn",
  },
  changePwd: {
    title: "Thay đổi mã pin",
    titleUpdatePwd: "Cập nhật mã pin",
    oldPass: "Mật khẩu cũ",
    oldPin: "Mã pin cũ",
    newPass: "Mã pin mới",
    confirmPwd: "Xác nhận ",
    currentNewPass: "Nhập lại mã pin mới",
    placeOldPass: "Nhập mật khẩu cũ",
    placeOldPin: "Nhập mã pin cũ",
    placeNewPass: "Nhập mã pin mới",
    button: "Xác nhận đổi mã pin",
    notifyContent: "Xác nhận đổi mã pin",
    notify: "Thông báo",
    successNotify: "Xác nhận đổi mã pin thành công",
  },
  account: {
    title: "Thông tin người dùng",
    hello: "Xin chào",
    invite: "Mời bạn bè",
    help: "Hỗ trợ",
    createSupport: "Tạo yêu cầu hỗ trợ",
    userManual: "Hướng dẫn sử dụng",
    commonQuestion: "Câu hỏi thường gặp",
    feedBack: "Góp ý",
    setting: "Thông tin cá nhân",
    logout: "Đăng xuất",
    support: "Hỗ trợ",
    accountDraw: "Tài khoản rút tiền",
    join: "Tham gia cộng đồng",
    passwordAndLogin: "Cài đặt và bảo mật",
    electricContract: "Hợp đồng điện tử",
    doneEKYC: "Đã xác thực chứng từ",
    errKYC: "Xác thực chứng từ thất bại",
    waitKYC: "Chờ xác thực chứng từ",
    confirmEKYC: "Vui lòng cập nhật chứng từ",
    logoutConfirm: "Bạn có chắc chắn muốn đăng xuất không?",
    notificationLogout: "Thông báo",
    linkSocialNetwork: "Liên kết mạng xã hội",
    uploadSuccess: "Cập nhật ảnh thành công",
    inviteCustom: "Mời khách hàng",
    takeCareCustom: "Chăm sóc khách hàng",
    infoConsult: "Thông tin người tư vấn",
    deleteAccount: "Xoá tài khoản",
    deleteAccountConfirm:
      "Bạn có chắc chắn muốn xoá tài khoản không?\nSau khi xoá tài khoản, bạn không thể đăng nhập vào ứng dụng được nữa. Vui lòng liên hệ Univest.vn để được hỗ trợ.",
  },
  information: {
    title: "Thông tin cá nhân",
    sex: "Giới tính",
    birthday: "Ngày sinh",
    phone: "Số điện thoại",
    address: "Địa chỉ",
    job: "Nghề nghiệp",
    taxId: "Mã số thuế",
    email: "Email",
    confirmAccount: "Thông tin chứng từ",
    up: "Mặt trước CMND",
    under: "Mặt sau CMND",
    fullName: "Họ và tên",
    city: "Thành phố",
    district: "Quận huyện",
    village: "Xã phường",
    keybook: "Mã sổ",
    avatar: "Ảnh chân dung",
  },
  identifyConfirm: {
    title: "Xác thực thông tin",
    avatar: "Ảnh chân dung",
    confirmAccount: "Thông tin chứng từ",
    up: "Mặt trước CMND",
    under: "Mặt sau CMND",
    photoIdentify: "Ảnh giấy tờ tuỳ thân",
    desIdentify1: "1. Mặt trước rõ đủ 4 góc",
    desIdentify2:
      "2. Không chụp giấy tờ tuỳ thân photo, chụp thông qua màn hình thiết bị điện tử",
    desAvatar1:
      "1. Chụp cận mặt, rõ thẳng góc, không bị che, không chụp quá xa",
    desAvatar2: "2. Không chụp chân dung từ ảnh, màn hình thiết bị điện tử",
    note: "Hãy xác thực chính xác thông tin của bạn để bắt đầu đầu tư. Sau khi tài khoản bạn được xác thực thành công, bạn không thể thực hiện xác thực lại. ",
    uploadSuccess: "Upload chứng từ thành công",
    updateIdentify: "Cập nhật chứng từ",
  },
  editProfile: {
    title: "Chỉnh sửa thông tin",
    updateInfo: "Cập nhật thông tin",
    updateSuccess: "Cập nhật thông tin thành công",
  },

  support: {
    title: "Hỗ trợ",
    contactFanPage: "Liên hệ qua Fanpage",
    contactZalo: "Liên hệ qua zalo",
    createRequest: "Tạo yêu cầu hỗ trợ",
    hotline: "Hotline",
    manual: "Hướng dẫn sử dụng",
    question: "Câu hỏi thường gặp",
    feedBack: "Góp ý cho Univest",
    policy: "Điều khoản sử dụng",
    questionScreen: "Những câu hỏi thương gặp",
    phone: "18006907",
  },
  paymentMethod: {
    title: "Chọn cách ",
    bank: "Chuyển khoản ngân hàng",
    vimo: "Ví điện tử Vimo",
    nganLuong: "Ví điện tử Ngân lượng",
    bankForm: "Ngân hàng",
    vimoForm: "Vimo",
    nganLuongForm: "Ngân lượng",
    payment: "Thanh toán",
    methodNotSupport: "Phương thức thanh toán chưa hỗ trợ",
    methodSupportDes: "Xin vui lòng lựa chọn phương thức thanh toán khác",
    paymentPending: "Giao dịch đang ở trạng thái chờ",
    paymentPendingDes:
      "Giao dịch với số tiền <b>%s VNĐ</b> đang ở trạng thái xử lý.",
    paymentSuccessfully: "Đầu tư thành công",
    paymentSuccessfullyDes:
      "Bạn đã đầu tư với số tiền <b>%s VNĐ</b> thành công.",
  },
  transaction: {
    types: ["Tất cả", "Nạp tiền", "Chờ nạp", "Rút tiền", "Chuyển đổi"],
    filter: "Bộ lọc",
    all: "Tất cả",
    accumulation: "Tích luỹ",
    chooseDate: "Chọn ngày",
    fromDate: "Từ ngày",
    toDate: "Đến ngày",
    source: "Nguồn tiền",
    target: "Nơi nhận",
    money: "Số tiền",
    status: "Trạng thái",
    sourceConvert: "Nguồn chuyển",
    targetConvert: "Nguồn nhận",
    code: "Mã sổ tiết kiệm",
    noData: "Bạn chưa có giao dịch nào",
    cancelSuccess: "Huỷ giao dịch thành công",
    success: "Thành công",
    cancelTransaction: "Bạn có chắc chắn huỷ giao dịch này không?",
  },
  invite: {
    header: "Liên kết khách hàng",
    title: "Các phương thức liên kết bạn và khách hàng",
    qrCode: "Quét Qr Code",
    inviteId: "Mã giới thiệu của bạn",
    link: "Link giới thiệu của bạn",
  },
  linkAccount: {
    header: "Thông tin tài khoản",
    accountNganLuong: "Tài khoản Ngân Lượng",
    accountViMo: "Tài khoản ViMo",
    accountBank: "Tài khoản ngân hàng",
    selectBank: "Chọn ngân hàng",
    linkNow: "Liên kết ngay",
    stkCode: "Số tài khoản",
    atmCode: "Số thẻ ATM",
    accountName: "Chủ tài khoản",
    updateSuccessBank: "Cập nhật tài khoản thành công!",
    addSuccessBank: "Thêm tài khoản thành công!",
    note: "<p><r>Chú ý</r>: Đây là tài khoản ngân hàng để thực hiện giao dịch, bạn cần đảm bảo thông tin tài khoản ngân hàng bạn cung cấp là chính xác. <r>Univest</r> sẽ không chịu trách nhiệm khi bạn nhập sai thông tin.</p>",
  },
  linkSocialNetwork: {
    linked: "Đã liên kết",
    notLinked: "Chưa liên kết",
    link: "Liên kết tài khoản",
    titleSocial: "Liên kết mạng xã hội",
    apple: "Apple",
    fb: "Facebook",
    google: "Google",
    notification: "Thông báo",
    desciption: "Vui lòng liên kết tài khoản mạng xã hội",
  },
  cashFlow: {
    title: "Dòng tiền",
  },
  notification: {
    title: "Thông báo",
    noNotify: "Không có thông báo.",
    types: ["Tất cả", "Hệ thống", "Giao dịch", "CTV", "Khác"],
    detail_title: "Nội dung thông báo",
    noData: "Bạn chưa có thông báo nào",
  },
  errorBiometryType: {
    NOT_DEFINE: "Vui lòng thêm ít nhất 1 vân tay vào thiết bị của bạn",
    // ios
    RCTTouchIDNotSupported: "Không hỗ trợ xác thực vân tay trên thiết bị này",
    RCTTouchIDUnknownError:
      "Đăng nhập thất bại nhiều lần, vui lòng đăng nhập với mật khẩu",
    LAErrorTouchIDNotEnrolled:
      "Vui lòng thêm ít nhất 1 xác thực vân tay vào thiết bị của bạn",
    LAErrorTouchIDNotAvailable:
      "Không có sẵn xác thực nhanh trên thiết bị của bạn",
    ErrorFaceId:
      "Vui lòng thêm ít nhất 1 xác thực Face ID vào thiết bị của bạn",
    // android
    NOT_SUPPORTED: "Không hỗ trợ xác thực vân tay trên thiết bị này",
    NOT_AVAILABLE: "Không hỗ trợ xác thực vân tay trên thiết bị này",
    NOT_ENROLLED:
      "Vui lòng thêm ít nhất 1 xác thực vân tay vào thiết bị của bạn",
    FINGERPRINT_ERROR_LOCKOUT_PERMANENT:
      "Xác thực không thành công, thử lại sau",
    errorWithTouchId:
      "Đăng nhập thất bại nhiều lần nhiều lần, vui lòng đăng nhập với mã PIN",
    LAErrorTouchIDLockout:
      "Đăng nhập thất bại quá nhiều lần, vui lòng thử lại sau",
  },
  setPassCode: {
    titleEnter: "Xác thực mã PIN",
    titleSetPasscode: "Sử dụng mã PIN để xác thực nhanh",
    repeat: "Nhập lại mã PIN",
    errorSet: "Mã PIN trước và mã PIN sau không trùng khớp",
    errorEnter: "Mã PIN không đúng",
    footerText: "Tiếp tục",
  },
  withdrawFromAccount: {
    titleScreen: "Rút tiền về tài khoản",
    detailTransaction: "Chi tiết giao dịch",
    formOfReceivingMoney: "Hình thức nhận tiền",
    beneficiaryName: "Ngân hàng thụ hưởng",
    receiver: "Người nhận",
    account: "Số tài khoản",
    moneyWithdraw: "Số tiền rút",
    date: "Ngày thực hiện",
    confirm: "Xác nhận",
    current: "VNĐ",
    bankTemplate: "Ngân hàng  VP Bank",
    withdrawSuccess: "Rút tiền thành công",
    alertSuccess: "Chúc mừng bạn đã rút thành công số tiền ",
    goAccount: "VNĐ về tài khoản.",
    withdrawFails: "Rút tiền thất bại",
    alertFails:
      "Rất tiếc giao dịch không thanh công, bạn hãy giao dịch lại hoặc gọi hỗ trợ.",
  },
  accumulatorBook: {
    title: "Danh sách sổ tích luỹ",
    having: "Đang có",
    draw: "Đã rút",
    pending: "Đang chờ",
  },
  investAccumulate: {
    header: "Đầu tư và tích luỹ",
    select: "Chọn gói tích luỹ bạn muốn đầu tư",
    confirmInvest: "Xác nhận đầu tư",
  },
  transferScreen: {
    title: "Chuyển khoản ngân hàng",
    description:
      "Để nạp tiền, bạn hãy dùng bất kỳ ngân hàng nào để chuyển khoản đến tài khoản sau: ",
    bank: "Ngân hàng nhận",
    receiver: "Tên tài khoản người nhận",
    account: "Số tài khoản nhận",
    money: "Số tiền cần chuyển",
    content: "Nội dung chuyển khoản",
    copy: "Sao chép",
    alert:
      "Nếu nội dung chuyển khoản thiếu hoặc không chính xác. Chúng tôi sẽ không thể nhận ra giao dịch của bạn.",
    or: "Hoặc thực hiện scan mã Qr code sau:",
    company: "Cong ty co phan cong nghe tai chinh Univest",
    bankName: "Ngân hàng",
    bankAccount: "Số tài khoản",
    downloadQrCode: "Tải ảnh QR-Code",
    pending: "Giao dịch đang chờ xử lý",
    pendingContent:
      "Giao dịch của bạn sẽ được xử lý trong vòng 10 phút kể từ khi chuyển khoản",
    transferred: "Tôi đã chuyển khoản",
    transferLater: "Tôi sẽ chuyển khoản sau",
    transferredTitle: "Cảm ơn bạn đã nạp tiền",
    transferredContent:
      "Univest sẽ gửi thông báo tới bạn sau vài phút ngay khi tài khoản của bạn nhận được tiền",
    transferLaterTitle: "Lệnh nạp tiền đang chờ",
    transferLaterContent:
      "Lệnh nạp tiền vẫn đang chờ bạn chuyển khoản. Bạn có thể xem lại lệnh nạp tiền của mình trong lịch sử giao dịch và nạp tiền bất cứ lúc nào.",
    goHome: "Trở về trang chủ",
  },
  update: {
    title: "Cập nhật phiên bản mới",
    description:
      "Đã có phiên bản cập nhật mới cho ứng dụng. Bạn vui lòng cập nhật để có trải nghiệm tốt hơn.\n\nXin cám ơn.",
    update: "Cập nhật",
    updating: "Đang cập nhật phiên bản mới",
    installing: "Đang cài đặt phiên bản mới",
  },
  maintain: {
    title: "Thông báo nâng cấp hệ thống",
    description:
      "Hệ thống hiện đang trong quá trình nâng cấp, xin quý nhà đầu tư thử lại sau. Xin cảm ơn!",
    update: "Đồng ý",
  },
  takeCareCustomer: {
    header: "Khách hàng chăm sóc",
    general: "Tổng quan",
    customer: "Khách hàng",
    totalMoney: "Tổng tiền đầu tư",
    totalCustomer: "Tổng số khách hàng",
    moneyChart: "Biểu đồ số dư trung bình NAV",
    moneyAverage: "Số dư trung bình",
    userChart: "Biểu đồ user mới",
    averageUser: "Số user trung bình",
    value: "Giá trị",
    first: "first",
    second: "second",
    time: "Thời gian",
    user: "User",
    listCustomer: "Danh sách khách hàng",
    customName: "Tên khách hàng",
    totalInvested: "Tổng đầu tư",
    phone: "Số điện thoại",
    email: "Email",
    address: "Địa chỉ",
  },
  consultantInfo: {
    title: "Thông tin người tư vấn",
    fullName: "Họ và tên",
    phoneNumber: "Số điện thoại",
    email: "Email",
    consultant: "Tư vấn viên",
    require: "Yêu cầu tư vấn",
    description:
      "Bạn chưa có tư vấn viên, bạn thêm tư vấn viên để giúp bạn có thêm thông tin đầu tư",
    id: "Mã tư vấn viên",
    enterId: "Nhập mã tư vấn viên",
    addConsultant: "Thêm tư vấn viên",
    titlePopup: "Trở thành cộng tác viên",
    descriptionPopup:
      "Ngân lượng muốn mời bạn trở thành cộng tác viên chăm sóc khách hàng",
  },
};

export default Languages;
